// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateCategoryResponse create category response
//
// swagger:model createCategoryResponse
type CreateCategoryResponse struct {

	// message
	// Example: Category created successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this create category response
func (m *CreateCategoryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create category response based on context it is used
func (m *CreateCategoryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateCategoryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateCategoryResponse) UnmarshalBinary(b []byte) error {
	var res CreateCategoryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
