// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateArticleResponse create article response
//
// swagger:model createArticleResponse
type CreateArticleResponse struct {

	// message
	// Example: Article created successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this create article response
func (m *CreateArticleResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create article response based on context it is used
func (m *CreateArticleResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateArticleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateArticleResponse) UnmarshalBinary(b []byte) error {
	var res CreateArticleResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
