// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateStreamPayload create stream payload
//
// swagger:model createStreamPayload
type CreateStreamPayload struct {

	// App of stream
	// Example: app
	// Required: true
	App *string `json:"app"`

	// Stream name of stream
	// Example: stream_name
	// Required: true
	StreamName *string `json:"stream_name"`
}

// Validate validates this create stream payload
func (m *CreateStreamPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStreamName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateStreamPayload) validateApp(formats strfmt.Registry) error {

	if err := validate.Required("app", "body", m.App); err != nil {
		return err
	}

	return nil
}

func (m *CreateStreamPayload) validateStreamName(formats strfmt.Registry) error {

	if err := validate.Required("stream_name", "body", m.StreamName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create stream payload based on context it is used
func (m *CreateStreamPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateStreamPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateStreamPayload) UnmarshalBinary(b []byte) error {
	var res CreateStreamPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
