// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteNewsCategoryResponse delete news category response
//
// swagger:model deleteNewsCategoryResponse
type DeleteNewsCategoryResponse struct {

	// message
	// Example: Category deleted successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this delete news category response
func (m *DeleteNewsCategoryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete news category response based on context it is used
func (m *DeleteNewsCategoryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteNewsCategoryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteNewsCategoryResponse) UnmarshalBinary(b []byte) error {
	var res DeleteNewsCategoryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
