// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteTVShowResponse delete t v show response
//
// swagger:model deleteTVShowResponse
type DeleteTVShowResponse struct {

	// message
	// Example: TV Show deleted successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this delete t v show response
func (m *DeleteTVShowResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete t v show response based on context it is used
func (m *DeleteTVShowResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteTVShowResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteTVShowResponse) UnmarshalBinary(b []byte) error {
	var res DeleteTVShowResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
