// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FaqPayload faq payload
//
// swagger:model faqPayload
type FaqPayload struct {

	// answer
	// Required: true
	Answer *string `json:"answer"`

	// question
	// Required: true
	Question *string `json:"question"`
}

// Validate validates this faq payload
func (m *FaqPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnswer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuestion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FaqPayload) validateAnswer(formats strfmt.Registry) error {

	if err := validate.Required("answer", "body", m.Answer); err != nil {
		return err
	}

	return nil
}

func (m *FaqPayload) validateQuestion(formats strfmt.Registry) error {

	if err := validate.Required("question", "body", m.Question); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this faq payload based on context it is used
func (m *FaqPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FaqPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FaqPayload) UnmarshalBinary(b []byte) error {
	var res FaqPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
