// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTVShowWithSchedulesResponse get t v show with schedules response
//
// swagger:model getTVShowWithSchedulesResponse
type GetTVShowWithSchedulesResponse struct {

	// schedules
	Schedules []*TVShowSchedule `json:"schedules"`

	// tv show
	TvShow *TVShow `json:"tv_show,omitempty"`
}

// Validate validates this get t v show with schedules response
func (m *GetTVShowWithSchedulesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSchedules(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTvShow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetTVShowWithSchedulesResponse) validateSchedules(formats strfmt.Registry) error {
	if swag.IsZero(m.Schedules) { // not required
		return nil
	}

	for i := 0; i < len(m.Schedules); i++ {
		if swag.IsZero(m.Schedules[i]) { // not required
			continue
		}

		if m.Schedules[i] != nil {
			if err := m.Schedules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("schedules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("schedules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GetTVShowWithSchedulesResponse) validateTvShow(formats strfmt.Registry) error {
	if swag.IsZero(m.TvShow) { // not required
		return nil
	}

	if m.TvShow != nil {
		if err := m.TvShow.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tv_show")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tv_show")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get t v show with schedules response based on the context it is used
func (m *GetTVShowWithSchedulesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSchedules(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTvShow(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetTVShowWithSchedulesResponse) contextValidateSchedules(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Schedules); i++ {

		if m.Schedules[i] != nil {

			if swag.IsZero(m.Schedules[i]) { // not required
				return nil
			}

			if err := m.Schedules[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("schedules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("schedules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GetTVShowWithSchedulesResponse) contextValidateTvShow(ctx context.Context, formats strfmt.Registry) error {

	if m.TvShow != nil {

		if swag.IsZero(m.TvShow) { // not required
			return nil
		}

		if err := m.TvShow.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tv_show")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tv_show")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetTVShowWithSchedulesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetTVShowWithSchedulesResponse) UnmarshalBinary(b []byte) error {
	var res GetTVShowWithSchedulesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
