// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetTVShowResponse get t v show response
//
// swagger:model getTVShowResponse
type GetTVShowResponse struct {

	// tv show
	TvShow *TVShow `json:"tv_show,omitempty"`
}

// Validate validates this get t v show response
func (m *GetTVShowResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTvShow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetTVShowResponse) validateTvShow(formats strfmt.Registry) error {
	if swag.IsZero(m.TvShow) { // not required
		return nil
	}

	if m.TvShow != nil {
		if err := m.TvShow.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tv_show")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tv_show")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get t v show response based on the context it is used
func (m *GetTVShowResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTvShow(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetTVShowResponse) contextValidateTvShow(ctx context.Context, formats strfmt.Registry) error {

	if m.TvShow != nil {

		if swag.IsZero(m.TvShow) { // not required
			return nil
		}

		if err := m.TvShow.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tv_show")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tv_show")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetTVShowResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetTVShowResponse) UnmarshalBinary(b []byte) error {
	var res GetTVShowResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
