// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetFeaturedSectionWithArticlesResponse get featured section with articles response
//
// swagger:model getFeaturedSectionWithArticlesResponse
type GetFeaturedSectionWithArticlesResponse struct {

	// articles
	Articles []*FeaturedArticle `json:"articles"`

	// section id
	// Example: 1
	SectionID int64 `json:"section_id,omitempty"`

	// section title
	// Example: Top Stories
	SectionTitle string `json:"section_title,omitempty"`
}

// Validate validates this get featured section with articles response
func (m *GetFeaturedSectionWithArticlesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArticles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetFeaturedSectionWithArticlesResponse) validateArticles(formats strfmt.Registry) error {
	if swag.IsZero(m.Articles) { // not required
		return nil
	}

	for i := 0; i < len(m.Articles); i++ {
		if swag.IsZero(m.Articles[i]) { // not required
			continue
		}

		if m.Articles[i] != nil {
			if err := m.Articles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("articles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("articles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get featured section with articles response based on the context it is used
func (m *GetFeaturedSectionWithArticlesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArticles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetFeaturedSectionWithArticlesResponse) contextValidateArticles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Articles); i++ {

		if m.Articles[i] != nil {

			if swag.IsZero(m.Articles[i]) { // not required
				return nil
			}

			if err := m.Articles[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("articles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("articles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetFeaturedSectionWithArticlesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetFeaturedSectionWithArticlesResponse) UnmarshalBinary(b []byte) error {
	var res GetFeaturedSectionWithArticlesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
