// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetFeaturedSectionsWithArticlesResponse get featured sections with articles response
//
// swagger:model getFeaturedSectionsWithArticlesResponse
type GetFeaturedSectionsWithArticlesResponse []*GetFeaturedSectionsWithArticlesResponseItems0

// Validate validates this get featured sections with articles response
func (m GetFeaturedSectionsWithArticlesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this get featured sections with articles response based on the context it is used
func (m GetFeaturedSectionsWithArticlesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if m[i] != nil {

			if swag.IsZero(m[i]) { // not required
				return nil
			}

			if err := m[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// GetFeaturedSectionsWithArticlesResponseItems0 get featured sections with articles response items0
//
// swagger:model GetFeaturedSectionsWithArticlesResponseItems0
type GetFeaturedSectionsWithArticlesResponseItems0 struct {

	// articles
	Articles []*GetFeaturedSectionWithArticlesResponseArticlesItems `json:"articles"`

	// featured section
	FeaturedSection *FeaturedSection `json:"featured_section,omitempty"`
}

// Validate validates this get featured sections with articles response items0
func (m *GetFeaturedSectionsWithArticlesResponseItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArticles(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFeaturedSection(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetFeaturedSectionsWithArticlesResponseItems0) validateArticles(formats strfmt.Registry) error {
	if swag.IsZero(m.Articles) { // not required
		return nil
	}

	for i := 0; i < len(m.Articles); i++ {
		if swag.IsZero(m.Articles[i]) { // not required
			continue
		}

		if m.Articles[i] != nil {
			if err := m.Articles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("articles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("articles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GetFeaturedSectionsWithArticlesResponseItems0) validateFeaturedSection(formats strfmt.Registry) error {
	if swag.IsZero(m.FeaturedSection) { // not required
		return nil
	}

	if m.FeaturedSection != nil {
		if err := m.FeaturedSection.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("featured_section")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("featured_section")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get featured sections with articles response items0 based on the context it is used
func (m *GetFeaturedSectionsWithArticlesResponseItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArticles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFeaturedSection(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetFeaturedSectionsWithArticlesResponseItems0) contextValidateArticles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Articles); i++ {

		if m.Articles[i] != nil {

			if swag.IsZero(m.Articles[i]) { // not required
				return nil
			}

			if err := m.Articles[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("articles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("articles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GetFeaturedSectionsWithArticlesResponseItems0) contextValidateFeaturedSection(ctx context.Context, formats strfmt.Registry) error {

	if m.FeaturedSection != nil {

		if swag.IsZero(m.FeaturedSection) { // not required
			return nil
		}

		if err := m.FeaturedSection.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("featured_section")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("featured_section")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetFeaturedSectionsWithArticlesResponseItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetFeaturedSectionsWithArticlesResponseItems0) UnmarshalBinary(b []byte) error {
	var res GetFeaturedSectionsWithArticlesResponseItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
