// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetFeaturedSectionWithArticlesResponseArticlesItems get featured section with articles response articles items
//
// swagger:model getFeaturedSectionWithArticlesResponseArticlesItems
type GetFeaturedSectionWithArticlesResponseArticlesItems struct {

	// ID of the article
	// Example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
	// Required: true
	ArticleID *string `json:"article_id"`

	// Timestamp when the article was created
	// Example: 2023-10-01T12:00:00Z
	// Required: true
	// Format: date-time
	CreatedAt *strfmt.DateTime `json:"created_at"`

	// ID of the featured section
	// Example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
	// Required: true
	FeaturedSectionID *string `json:"featured_section_id"`

	// ID of the featured article
	// Example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
	// Required: true
	// Format: uuid4
	ID *strfmt.UUID4 `json:"id"`

	// Timestamp when the article was last updated
	// Example: 2023-10-02T12:00:00Z
	// Required: true
	// Format: date-time
	UpdatedAt *strfmt.DateTime `json:"updated_at"`
}

// Validate validates this get featured section with articles response articles items
func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArticleID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFeaturedSectionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) validateArticleID(formats strfmt.Registry) error {

	if err := validate.Required("article_id", "body", m.ArticleID); err != nil {
		return err
	}

	return nil
}

func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) validateFeaturedSectionID(formats strfmt.Registry) error {

	if err := validate.Required("featured_section_id", "body", m.FeaturedSectionID); err != nil {
		return err
	}

	return nil
}

func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.FormatOf("id", "body", "uuid4", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("updated_at", "body", m.UpdatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get featured section with articles response articles items based on context it is used
func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetFeaturedSectionWithArticlesResponseArticlesItems) UnmarshalBinary(b []byte) error {
	var res GetFeaturedSectionWithArticlesResponseArticlesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
