// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlanPayload plan payload
//
// swagger:model planPayload
type PlanPayload struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// features
	// Required: true
	Features *string `json:"features"`

	// is active
	IsActive bool `json:"isActive,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// price monthly
	// Required: true
	PriceMonthly *string `json:"priceMonthly"`

	// price yearly
	// Required: true
	PriceYearly *string `json:"priceYearly"`
}

// Validate validates this plan payload
func (m *PlanPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFeatures(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePriceMonthly(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePriceYearly(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlanPayload) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *PlanPayload) validateFeatures(formats strfmt.Registry) error {

	if err := validate.Required("features", "body", m.Features); err != nil {
		return err
	}

	return nil
}

func (m *PlanPayload) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *PlanPayload) validatePriceMonthly(formats strfmt.Registry) error {

	if err := validate.Required("priceMonthly", "body", m.PriceMonthly); err != nil {
		return err
	}

	return nil
}

func (m *PlanPayload) validatePriceYearly(formats strfmt.Registry) error {

	if err := validate.Required("priceYearly", "body", m.PriceYearly); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this plan payload based on context it is used
func (m *PlanPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlanPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlanPayload) UnmarshalBinary(b []byte) error {
	var res PlanPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
