// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateTagResponse update tag response
//
// swagger:model updateTagResponse
type UpdateTagResponse struct {

	// message
	// Example: Tag updated successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this update tag response
func (m *UpdateTagResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update tag response based on context it is used
func (m *UpdateTagResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateTagResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateTagResponse) UnmarshalBinary(b []byte) error {
	var res UpdateTagResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
