// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateArticleResponse update article response
//
// swagger:model updateArticleResponse
type UpdateArticleResponse struct {

	// message
	// Example: Article updated successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this update article response
func (m *UpdateArticleResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update article response based on context it is used
func (m *UpdateArticleResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateArticleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateArticleResponse) UnmarshalBinary(b []byte) error {
	var res UpdateArticleResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
