// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateCategoryResponse update category response
//
// swagger:model updateCategoryResponse
type UpdateCategoryResponse struct {

	// message
	// Example: Category updated successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this update category response
func (m *UpdateCategoryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update category response based on context it is used
func (m *UpdateCategoryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateCategoryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateCategoryResponse) UnmarshalBinary(b []byte) error {
	var res UpdateCategoryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
