// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateStreamPayload update stream payload
//
// swagger:model updateStreamPayload
type UpdateStreamPayload struct {

	// live description
	LiveDescription string `json:"liveDescription,omitempty"`

	// live title
	LiveTitle string `json:"liveTitle,omitempty"`

	// thumbnail
	Thumbnail string `json:"thumbnail,omitempty"`
}

// Validate validates this update stream payload
func (m *UpdateStreamPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update stream payload based on context it is used
func (m *UpdateStreamPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateStreamPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateStreamPayload) UnmarshalBinary(b []byte) error {
	var res UpdateStreamPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
