// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateTVShowScheduleResponse update t v show schedule response
//
// swagger:model updateTVShowScheduleResponse
type UpdateTVShowScheduleResponse struct {

	// message
	// Example: TV Show schedule updated successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this update t v show schedule response
func (m *UpdateTVShowScheduleResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update t v show schedule response based on context it is used
func (m *UpdateTVShowScheduleResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateTVShowScheduleResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateTVShowScheduleResponse) UnmarshalBinary(b []byte) error {
	var res UpdateTVShowScheduleResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
