// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateTVShowResponse update t v show response
//
// swagger:model updateTVShowResponse
type UpdateTVShowResponse struct {

	// message
	// Example: TV Show updated successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this update t v show response
func (m *UpdateTVShowResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update t v show response based on context it is used
func (m *UpdateTVShowResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateTVShowResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateTVShowResponse) UnmarshalBinary(b []byte) error {
	var res UpdateTVShowResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
