// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateFeaturedArticlesResponse update featured articles response
//
// swagger:model updateFeaturedArticlesResponse
type UpdateFeaturedArticlesResponse struct {

	// message
	// Example: Featured Section articles updated successfully.
	Message string `json:"message,omitempty"`
}

// Validate validates this update featured articles response
func (m *UpdateFeaturedArticlesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update featured articles response based on context it is used
func (m *UpdateFeaturedArticlesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateFeaturedArticlesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateFeaturedArticlesResponse) UnmarshalBinary(b []byte) error {
	var res UpdateFeaturedArticlesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
