swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths:
  /swagger.yml:
    get:
      summary: Get swagger.yml
      operationId: GetSwaggerRoute
      produces:
        - text/plain
      description: |-
        OpenAPI Specification ver. 2 (fka Swagger)
        Returns our handcrafted and validated `swagger.yml`.
      tags:
        - common
      responses:
        "200":
          description: OK
  /api/v1/healthy:
    get:
      summary: Get healthy
      operationId: GetHealthyRoute
      produces:
        - text/plain
      description: |-
        This endpoint returns 200 when the service is healthy.
        Returns an human readable string about the current service status.
      tags:
        - common
      responses:
        "200":
          description: Ready.
        "521":
          description: Not ready.
  /api/v1/version:
    get:
      summary: Get version
      operationId: GetVersionRoute
      produces:
        - text/plain
      description: |-
        This endpoint returns the module name, commit and build-date baked into the app binary.
      tags:
        - common
      responses:
        "200":
          description: "ModuleName @ Commit (BuildDate)"
  /api/v1/upload/image:
    post:
      tags:
        - common
      summary: Upload an image
      description: Upload an image file. Supports JPEG, PNG, GIF, and WebP formats.
      operationId: postUploadImage
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: image
          in: formData
          description: The image file to upload
          required: true
          type: file
      responses:
        200:
          description: Image uploaded successfully
          schema:
            $ref: "../definitions/common.yml#/definitions/ImageUploadResponse"
