swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths:
  /api/v1/news:
    post:
      description: Creates a news article
      tags:
        - news
      summary: Creates a news article
      operationId: PostCreateNewsArticle
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/news.yml#/definitions/CreateNewsArticleRequest"
      responses:
        "200":
          description: CreateNewsArticleResponse
          schema:
            $ref: "../definitions/news.yml#/definitions/CreateNewsArticleResponse"
    get:
      description: Retrieves all news articles
      tags:
        - news
      summary: Gets all news articles
      operationId: GetAllNewsArticles
      responses:
        "200":
          description: List of news articles
          schema:
            $ref: "../definitions/news.yml#/definitions/GetAllNewsArticleResponse"
  /api/v1/news/{id}:
    get:
      description: Retrieves a news article by ID
      tags:
        - news
      summary: Gets a news article
      operationId: GetNewsArticle
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID of the news article
      responses:
        "200":
          description: GetNewsArticleResponse
          schema:
            $ref: "../definitions/news.yml#/definitions/GetNewsArticleResponse"
    put:
      description: Updates a news article by ID
      tags:
        - news
      summary: Updates a news article
      operationId: UpdateNewsArticle
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID of the news article
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/news.yml#/definitions/UpdateNewsArticleRequest"
      responses:
        "200":
          description: UpdateNewsArticleResponse
          schema:
            $ref: "../definitions/news.yml#/definitions/UpdateNewsArticleResponse"
    delete:
      description: Deletes a news article by ID
      tags:
        - news
      summary: Deletes a news article
      operationId: DeleteNewsArticle
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID of the news article
      responses:
        "200":
          description: DeleteNewsArticleResponse
          schema:
            $ref: "../definitions/news.yml#/definitions/DeleteNewsArticleResponse"
