swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths:
  /api/v1/news/categories:
    post:
      description: Creates a news category
      tags:
        - news_categories
      summary: Creates a news category
      operationId: PostCreateNewsCategory
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/news_category.yml#/definitions/NewsCategory"
      responses:
        "200":
          description: CreateNewsCategoryResponse
          schema:
            $ref: "../definitions/news_category.yml#/definitions/CreateNewsCategoryResponse"
    get:
      description: Retrieves all categories with their associated news articles
      tags:
        - news_categories
      summary: Gets all categories with news
      operationId: GetAllCategoriesWithNews
      responses:
        "200":
          description: List of categories with news
          schema:
            $ref: "../definitions/news_category.yml#/definitions/GetAllCategoriesWithNewsResponse"
  /api/v1/news/categories/{id}:
    get:
      description: Retrieves a news category by ID
      tags:
        - news_categories
      summary: Gets a news category
      operationId: GetNewsCategory
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID of the news category
      responses:
        "200":
          description: GetNewsCategoryResponse
          schema:
            $ref: "../definitions/news_category.yml#/definitions/GetNewsCategoryResponse"
    put:
      description: Updates a news category by ID
      tags:
        - news_categories
      summary: Updates a news category
      operationId: UpdateNewsCategory
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID of the news category
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/news_category.yml#/definitions/NewsCategory"
      responses:
        "200":
          description: UpdateNewsCategoryResponse
          schema:
            $ref: "../definitions/news_category.yml#/definitions/UpdateNewsCategoryResponse"
    delete:
      description: Deletes a news category by ID
      tags:
        - news_categories
      summary: Deletes a news category
      operationId: DeleteNewsCategory
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID of the news category
      responses:
        "200":
          description: DeleteNewsCategoryResponse
          schema:
            $ref: "../definitions/news_category.yml#/definitions/DeleteNewsCategoryResponse"
  /api/v1/news/categories/{id}/news:
    get:
      description: Retrieves a category with its associated news articles
      tags:
        - news_categories
      summary: Gets a category with news
      operationId: GetCategoryWithNews
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: ID of the news category
      responses:
        "200":
          description: GetCategoryWithNewsResponse
          schema:
            $ref: "../definitions/news_category.yml#/definitions/GetCategoryWithNewsResponse"
