swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths:
  /api/v1/streams:
    post:
      description: Creates a stream
      tags:
        - stream
      summary: Creates a stream
      operationId: PostCreateStreamRoute
      responses:
        "200":
          description: PostCreateStreamResponse
          schema:
            $ref: "../definitions/stream.yml#/definitions/CreateStreamResponse"
  /api/v1/streams/publish:
    post:
      description: Publishes a stream
      tags:
        - stream
      summary: Publishes a stream
      operationId: PostPublishStreamRoute
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/stream.yml#/definitions/StreamEvent"
      responses:
        "200":
          description: PostPublishResponse
          schema:
            $ref: "../definitions/stream.yml#/definitions/StreamEventResponse"
  /api/v1/streams/unpublish:
    post:
      description: Unpublishes a stream
      tags:
        - stream
      summary: Unpublishes a stream
      operationId: PostUnpublishStreamRoute
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/stream.yml#/definitions/StreamEvent"
      responses:
        "200":
          description: PostUnpublishResponse
          schema:
            $ref: "../definitions/stream.yml#/definitions/StreamEventResponse"
  /api/v1/streams/play:
    post:
      description: Plays a stream
      tags:
        - stream
      summary: Plays a stream
      operationId: PostPlayStreamRoute
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/stream.yml#/definitions/StreamEvent"
      responses:
        "200":
          description: PostPublishResponse
          schema:
            $ref: "../definitions/stream.yml#/definitions/StreamEventResponse"
  /api/v1/streams/stop:
    post:
      description: Stops a stream
      tags:
        - stream
      summary: Stops a stream
      operationId: PostStopStreamRoute
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/stream.yml#/definitions/StreamEvent"
      responses:
        "200":
          description: PostStopStreamResponse
          schema:
            $ref: "../definitions/stream.yml#/definitions/StreamEventResponse"
