// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: articles.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, content, category_id, image, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, content, category_id, created_at, updated_at
`

type CreateArticleParams struct {
	Title       string
	Content     string
	CategoryID  uuid.NullUUID
	Image       string
	Description sql.NullString
}

type CreateArticleRow struct {
	ID         uuid.UUID
	Title      string
	Content    string
	CategoryID uuid.NullUUID
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Content,
		arg.CategoryID,
		arg.Image,
		arg.Description,
	)
	var i CreateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const getAllArticles = `-- name: GetAllArticles :many
SELECT id, title, description, content, image, category_id, created_at, updated_at
FROM articles
ORDER BY created_at DESC
`

func (q *Queries) GetAllArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, getAllArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Image,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticle = `-- name: GetArticle :one
SELECT id, title, description, content, image, category_id, created_at, updated_at
FROM articles
WHERE id = $1
`

func (q *Queries) GetArticle(ctx context.Context, id uuid.UUID) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Content,
		&i.Image,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticlesByCategoryID = `-- name: GetArticlesByCategoryID :many
SELECT id, title, description, content, image, category_id, created_at, updated_at
FROM articles 
WHERE category_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetArticlesByCategoryID(ctx context.Context, categoryID uuid.NullUUID) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, getArticlesByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Content,
			&i.Image,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = $1, content = $2, category_id = $3, image = $4, description = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $6
RETURNING id, title, content, category_id, created_at, updated_at
`

type UpdateArticleParams struct {
	Title       string
	Content     string
	CategoryID  uuid.NullUUID
	Image       string
	Description sql.NullString
	ID          uuid.UUID
}

type UpdateArticleRow struct {
	ID         uuid.UUID
	Title      string
	Content    string
	CategoryID uuid.NullUUID
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.Title,
		arg.Content,
		arg.CategoryID,
		arg.Image,
		arg.Description,
		arg.ID,
	)
	var i UpdateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
