// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: featured_sections.sql

package database

import (
	"context"
	"database/sql"
)

const createFeaturedArticle = `-- name: CreateFeaturedArticle :one
INSERT INTO featured_articles (featured_section_id, news_id)
VALUES ($1, $2)
RETURNING id, featured_section_id, news_id, created_at, updated_at
`

type CreateFeaturedArticleParams struct {
	FeaturedSectionID sql.NullInt32
	NewsID            sql.NullInt32
}

func (q *Queries) CreateFeaturedArticle(ctx context.Context, arg CreateFeaturedArticleParams) (FeaturedArticle, error) {
	row := q.db.QueryRowContext(ctx, createFeaturedArticle, arg.FeaturedSectionID, arg.NewsID)
	var i FeaturedArticle
	err := row.Scan(
		&i.ID,
		&i.FeaturedSectionID,
		&i.NewsID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFeaturedSection = `-- name: CreateFeaturedSection :one
INSERT INTO featured_sections (title)
VALUES ($1)
RETURNING id, title, created_at, updated_at
`

func (q *Queries) CreateFeaturedSection(ctx context.Context, title string) (FeaturedSection, error) {
	row := q.db.QueryRowContext(ctx, createFeaturedSection, title)
	var i FeaturedSection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeaturedArticle = `-- name: DeleteFeaturedArticle :exec
DELETE FROM featured_articles
WHERE id = $1
`

func (q *Queries) DeleteFeaturedArticle(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFeaturedArticle, id)
	return err
}

const deleteFeaturedSection = `-- name: DeleteFeaturedSection :exec
DELETE FROM featured_sections
WHERE id = $1
`

func (q *Queries) DeleteFeaturedSection(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFeaturedSection, id)
	return err
}

const getAllFeaturedSectionsWithArticles = `-- name: GetAllFeaturedSectionsWithArticles :many
SELECT 
    fs.id AS section_id,
    fs.title AS section_title,
    fa.id AS featured_article_id,
    fa.news_id AS news_id,
    n.title AS news_title,
    n.content AS news_content,
    fa.created_at AS featured_article_created_at,
    fa.updated_at AS featured_article_updated_at
FROM 
    featured_sections fs
LEFT JOIN 
    featured_articles fa ON fs.id = fa.featured_section_id
LEFT JOIN 
    news n ON fa.news_id = n.id
ORDER BY 
    fs.title, fa.created_at DESC
`

type GetAllFeaturedSectionsWithArticlesRow struct {
	SectionID                int32
	SectionTitle             string
	FeaturedArticleID        sql.NullInt32
	NewsID                   sql.NullInt32
	NewsTitle                sql.NullString
	NewsContent              sql.NullString
	FeaturedArticleCreatedAt sql.NullTime
	FeaturedArticleUpdatedAt sql.NullTime
}

func (q *Queries) GetAllFeaturedSectionsWithArticles(ctx context.Context) ([]GetAllFeaturedSectionsWithArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeaturedSectionsWithArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFeaturedSectionsWithArticlesRow
	for rows.Next() {
		var i GetAllFeaturedSectionsWithArticlesRow
		if err := rows.Scan(
			&i.SectionID,
			&i.SectionTitle,
			&i.FeaturedArticleID,
			&i.NewsID,
			&i.NewsTitle,
			&i.NewsContent,
			&i.FeaturedArticleCreatedAt,
			&i.FeaturedArticleUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturedArticle = `-- name: GetFeaturedArticle :one
SELECT id, featured_section_id, news_id, created_at, updated_at
FROM featured_articles
WHERE id = $1
`

func (q *Queries) GetFeaturedArticle(ctx context.Context, id int32) (FeaturedArticle, error) {
	row := q.db.QueryRowContext(ctx, getFeaturedArticle, id)
	var i FeaturedArticle
	err := row.Scan(
		&i.ID,
		&i.FeaturedSectionID,
		&i.NewsID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeaturedArticlesBySection = `-- name: GetFeaturedArticlesBySection :many
SELECT id, featured_section_id, news_id, created_at, updated_at
FROM featured_articles
WHERE featured_section_id = $1
`

func (q *Queries) GetFeaturedArticlesBySection(ctx context.Context, featuredSectionID sql.NullInt32) ([]FeaturedArticle, error) {
	rows, err := q.db.QueryContext(ctx, getFeaturedArticlesBySection, featuredSectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeaturedArticle
	for rows.Next() {
		var i FeaturedArticle
		if err := rows.Scan(
			&i.ID,
			&i.FeaturedSectionID,
			&i.NewsID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturedSection = `-- name: GetFeaturedSection :one
SELECT id, title, created_at, updated_at
FROM featured_sections
WHERE id = $1
`

func (q *Queries) GetFeaturedSection(ctx context.Context, id int32) (FeaturedSection, error) {
	row := q.db.QueryRowContext(ctx, getFeaturedSection, id)
	var i FeaturedSection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeaturedSectionWithArticles = `-- name: GetFeaturedSectionWithArticles :one
SELECT 
    fs.id AS section_id,
    fs.title AS section_title,
    fa.id AS featured_article_id,
    fa.news_id AS news_id,
    n.title AS news_title,
    n.content AS news_content,
    fa.created_at AS featured_article_created_at,
    fa.updated_at AS featured_article_updated_at
FROM 
    featured_sections fs
LEFT JOIN 
    featured_articles fa ON fs.id = fa.featured_section_id
LEFT JOIN 
    news n ON fa.news_id = n.id
WHERE 
    fs.id = $1  -- Pass the featured section ID as a parameter
ORDER BY 
    fa.created_at DESC
`

type GetFeaturedSectionWithArticlesRow struct {
	SectionID                int32
	SectionTitle             string
	FeaturedArticleID        sql.NullInt32
	NewsID                   sql.NullInt32
	NewsTitle                sql.NullString
	NewsContent              sql.NullString
	FeaturedArticleCreatedAt sql.NullTime
	FeaturedArticleUpdatedAt sql.NullTime
}

func (q *Queries) GetFeaturedSectionWithArticles(ctx context.Context, id int32) (GetFeaturedSectionWithArticlesRow, error) {
	row := q.db.QueryRowContext(ctx, getFeaturedSectionWithArticles, id)
	var i GetFeaturedSectionWithArticlesRow
	err := row.Scan(
		&i.SectionID,
		&i.SectionTitle,
		&i.FeaturedArticleID,
		&i.NewsID,
		&i.NewsTitle,
		&i.NewsContent,
		&i.FeaturedArticleCreatedAt,
		&i.FeaturedArticleUpdatedAt,
	)
	return i, err
}

const updateFeaturedArticle = `-- name: UpdateFeaturedArticle :one
UPDATE featured_articles
SET featured_section_id = $1, news_id = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, featured_section_id, news_id, created_at, updated_at
`

type UpdateFeaturedArticleParams struct {
	FeaturedSectionID sql.NullInt32
	NewsID            sql.NullInt32
	ID                int32
}

func (q *Queries) UpdateFeaturedArticle(ctx context.Context, arg UpdateFeaturedArticleParams) (FeaturedArticle, error) {
	row := q.db.QueryRowContext(ctx, updateFeaturedArticle, arg.FeaturedSectionID, arg.NewsID, arg.ID)
	var i FeaturedArticle
	err := row.Scan(
		&i.ID,
		&i.FeaturedSectionID,
		&i.NewsID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFeaturedSection = `-- name: UpdateFeaturedSection :one
UPDATE featured_sections
SET title = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, title, created_at, updated_at
`

type UpdateFeaturedSectionParams struct {
	Title string
	ID    int32
}

func (q *Queries) UpdateFeaturedSection(ctx context.Context, arg UpdateFeaturedSectionParams) (FeaturedSection, error) {
	row := q.db.QueryRowContext(ctx, updateFeaturedSection, arg.Title, arg.ID)
	var i FeaturedSection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
