services:
  oryx:
    image: ossrs/oryx:5
    container_name: oryx
    restart: always
    ports:
      - "80:2022"
      - "443:2443"
      - "1935:1935"
      - "8000:8000/udp"
      - "10080:10080/udp"
    volumes:
      - "${HOME}/data:/data"
    stdin_open: true
    tty: true
