// Code generated by go-swagger; DO NOT EDIT.

package stream

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPostVLiveSourceRouteMixin9Params creates a new PostVLiveSourceRouteMixin9Params object
// no default values defined in spec.
func NewPostVLiveSourceRouteMixin9Params() PostVLiveSourceRouteMixin9Params {

	return PostVLiveSourceRouteMixin9Params{}
}

// PostVLiveSourceRouteMixin9Params contains all the bound params for the post v live source route mixin9 operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostVLiveSourceRouteMixin9
type PostVLiveSourceRouteMixin9Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostVLiveSourceRouteMixin9Params() beforehand.
func (o *PostVLiveSourceRouteMixin9Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostVLiveSourceRouteMixin9Params) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
