// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetCategoryWithArticlesMixin2Params creates a new GetCategoryWithArticlesMixin2Params object
// no default values defined in spec.
func NewGetCategoryWithArticlesMixin2Params() GetCategoryWithArticlesMixin2Params {

	return GetCategoryWithArticlesMixin2Params{}
}

// GetCategoryWithArticlesMixin2Params contains all the bound params for the get category with articles mixin2 operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCategoryWithArticlesMixin2
type GetCategoryWithArticlesMixin2Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCategoryWithArticlesMixin2Params() beforehand.
func (o *GetCategoryWithArticlesMixin2Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCategoryWithArticlesMixin2Params) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
