// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetCategoryWithArticlesParams creates a new GetCategoryWithArticlesParams object
// no default values defined in spec.
func NewGetCategoryWithArticlesParams() GetCategoryWithArticlesParams {

	return GetCategoryWithArticlesParams{}
}

// GetCategoryWithArticlesParams contains all the bound params for the get category with articles operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCategoryWithArticles
type GetCategoryWithArticlesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCategoryWithArticlesParams() beforehand.
func (o *GetCategoryWithArticlesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCategoryWithArticlesParams) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
