// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetTagWithArticlesMixin9Params creates a new GetTagWithArticlesMixin9Params object
// no default values defined in spec.
func NewGetTagWithArticlesMixin9Params() GetTagWithArticlesMixin9Params {

	return GetTagWithArticlesMixin9Params{}
}

// GetTagWithArticlesMixin9Params contains all the bound params for the get tag with articles mixin9 operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetTagWithArticlesMixin9
type GetTagWithArticlesMixin9Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTagWithArticlesMixin9Params() beforehand.
func (o *GetTagWithArticlesMixin9Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTagWithArticlesMixin9Params) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
