swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths: {}
definitions:
  User:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        format: uuid4
        description: ID of user
        example: 891d37d3-c74f-493e-aea8-af73efd92016
  PostLoginPayload:
    type: object
    required:
      - email
      - password
    properties:
      password:
        description: Password of user to authenticate as
        type: string
        maxLength: 255
        minLength: 1
        example: correct horse battery staple
      email:
        description: Email of user to authenticate as
        type: string
        format: email
        maxLength: 255
        minLength: 1
        example: user@example.com
  PostLoginResponse:
    type: object
    required:
      - access_token
      - refresh_token
    properties:
      access_token:
        description: Access token required for accessing protected API endpoints
        type: string
        example: "eyJhdWQiOiJjdXN0b2..."
      refresh_token:
        description: Refresh token for refreshing the access token once it expires
        type: string
        example: "eyJhdWQiOiJjdXN0b2..."
  PostRegisterPayload:
    type: object
    required:
      - name
      - email
      - password
    properties:
      password:
        description: Password to register with
        type: string
        maxLength: 255
        minLength: 1
        example: correct horse battery staple
      email:
        description: Email to register with
        type: string
        format: email
        maxLength: 255
        minLength: 1
        example: user@example.com
      name:
        description: Name to register with
        type: string
        maxLength: 255
        minLength: 1
        example: John Doe
