swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths: {}
definitions:
  Paginatable:
    type: object
    required:
      - limit
      - offset
      - total
    properties:
      limit:
        type: integer
        description: Actual limit applied to request
      offset:
        type: integer
        description: Actual offset applied to request
      total:
        type: integer
        description: Total number of records available
  ImageUploadResponse:
    type: object
    required:
      - url
      - filename
    properties:
      url:
        type: string
        description: The URL path where the uploaded image can be accessed
        example: /assets/images/550e8400-e29b-41d4-a716-446655440000.jpg
      filename:
        type: string
        description: The unique filename of the uploaded image
        example: 550e8400-e29b-41d4-a716-446655440000.jpg
parameters:
  offsetParam:
    type: integer
    in: query
    name: offset
    description: Offset used for pagination, number of records to skip
    default: 0
    minimum: 0
  limitParam:
    type: integer
    in: query
    name: limit
    description: Limit used for pagination, number of records to retrieve
    default: 50
    minimum: 1
    maximum: 500
  orderDirParam:
    type: string
    in: query
    name: orderDir
    description: Direction of order applied, defaults to `asc` if omitted. `asc` will sort `NULL` values at the end of the list.
    enum:
      - asc
      - desc
    default: asc
