swagger: "2.0"
info:
  title: ""
  version: 0.1.0
paths: {}
definitions:
  Faq:
    type: object
    required:
      - id
      - question
      - answer
    properties:
      id:
        type: string
        format: uuid4
      question:
        type: string
      answer:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string

  FaqPayload:
    type: object
    required:
      - question
      - answer
    properties:
      question:
        type: string
      answer:
        type: string

  FaqList:
    type: array
    items: 
      $ref: "#/definitions/Faq"
