swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths: {}
definitions:
  FeaturedSection:
    type: object
    required:
      - id
      - title
      - created_at
      - updated_at
    properties:
      id:
        type: string
        description: ID of section
        format: uuid4
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      title:
        type: string
        description: Title of the featured section
        example: "Top Stories"
      created_at:
        type: string
        format: date-time
        description: Timestamp when the section was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the section was last updated
        example: "2023-10-02T12:00:00Z"
  CreateFeaturedSectionRequest:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        description: Title of the featured section
  CreateFeaturedSectionResponse:
    type: object
    properties:
      message:
        type: string
        example: "Featured section created successfully."
  GetFeaturedSectionResponse:
    type: object
    properties:
      section:
        $ref: "#/definitions/FeaturedSection"
  GetFeaturedSectionsResponse:
    type: array
    items:
      $ref: "#/definitions/FeaturedSection"
  UpdateFeaturedSectionRequest:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        description: Title of the featured section
  UpdateFeaturedSectionResponse:
    type: object
    properties:
      message:
        type: string
        example: "Featured Section updated successfully."
  DeleteFeaturedSectionResponse:
    type: object
    properties:
      message:
        type: string
        example: "Section deleted successfully."
  Article:
    type: object
    required:
      - id
      - featured_section_id
      - article_id
      - created_at
      - updated_at
    properties:
      id:
        type: string
        format: uuid4
        description: ID of the featured article
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      featured_section_id:
        type: string
        description: ID of the featured section
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      article_id:
        type: string
        description: ID of the article
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      created_at:
        type: string
        format: date-time
        description: Timestamp when the article was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the article was last updated
        example: "2023-10-02T12:00:00Z"
  GetFeaturedSectionWithArticlesResponse:
    type: object
    properties:
      featured_section:
        type: object
        $ref: "#/definitions/FeaturedSection"
      articles:
        type: array
        items:
          $ref: "#/definitions/Article"
  GetFeaturedSectionsWithArticlesResponse:
    type: array
    items:
      type: object
      properties:
        featured_section:
          $ref: "#/definitions/FeaturedSection"
        articles:
          type: array
          items:
            $ref: "#/definitions/Article"
