swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths: {}
definitions:
  FeaturedSection:
    type: object
    required:
      - id
      - title
      - created_at
      - updated_at
    properties:
      id:
        type: integer
        description: ID of the featured section
        example: 1
      title:
        type: string
        description: Title of the featured section
        example: "Top Stories"
      created_at:
        type: string
        format: date-time
        description: Timestamp when the section was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the section was last updated
        example: "2023-10-02T12:00:00Z"
  CreateFeaturedSectionResponse:
    type: object
    required:
      - id
      - title
      - created_at
      - updated_at
    properties:
      id:
        type: integer
        description: ID of the created featured section
        example: 1
      title:
        type: string
        description: Title of the created featured section
        example: "Top Stories"
      created_at:
        type: string
        format: date-time
        description: Timestamp when the section was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the section was last updated
        example: "2023-10-02T12:00:00Z"
  GetFeaturedSectionResponse:
    type: object
    properties:
      section:
        $ref: "#/definitions/FeaturedSection"
  UpdateFeaturedSectionResponse:
    type: object
    properties:
      section:
        $ref: "#/definitions/FeaturedSection"
  DeleteFeaturedSectionResponse:
    type: object
    properties:
      message:
        type: string
        example: "Section deleted successfully."
  FeaturedArticle:
    type: object
    required:
      - id
      - featured_section_id
      - news_id
      - created_at
      - updated_at
    properties:
      id:
        type: integer
        description: ID of the featured article
        example: 1
      featured_section_id:
        type: integer
        description: ID of the featured section
        example: 1
      news_id:
        type: integer
        description: ID of the news article
        example: 1
      created_at:
        type: string
        format: date-time
        description: Timestamp when the article was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the article was last updated
        example: "2023-10-02T12:00:00Z"
  GetFeaturedSectionWithArticlesResponse:
    type: object
    properties:
      section_id:
        type: integer
        example: 1
      section_title:
        type: string
        example: "Top Stories"
      articles:
        type: array
        items:
          $ref: "#/definitions/FeaturedArticle"
  GetAllFeaturedSectionsWithArticlesResponse:
    type: array
    items:
      type: object
      properties:
        section_id:
          type: integer
          example: 1
        section_title:
          type: string
          example: "Top Stories"
        featured_article_id:
          type: integer
          example: 1
        news_id:
          type: integer
          example: 1
        news_title:
          type: string
          example: "Breaking News Title"
        news_content:
          type: string
          example: "This is the content of the news article."
        featured_article_created_at:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        featured_article_updated_at:
          type: string
          format: date-time
          example: "2023-10-02T12:00:00Z"
