swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths: {}
definitions:
  FeaturedSection:
    type: object
    required:
      - id
      - title
      - app_id
    properties:
      id:
        type: string
        description: ID of section
        format: uuid4
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      app_id:
        type: string
        format: uuid4
        description: ID of app
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      title:
        type: string
        description: Title of the featured section
        example: "Top Stories"
      created_at:
        type: string
        format: date-time
        description: Timestamp when the section was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the section was last updated
        example: "2023-10-02T12:00:00Z"
  Article:
    type: object
    required:
      - id
      - title
      - content
      - image
      - app_id
    properties:
      id:
        type: string
        format: uuid4
        description: ID of article
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      app_id:
        type: string
        format: uuid4
        description: ID of app
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      title:
        type: string
        description: Title of the article
        maxLength: 255
        example: "Article Title"
      content:
        type: string
        description: Content of the article
        example: "This is the content of the article."
      tags:
        type: string
        description: Content of the article
        example: "tag1,tag2,tag3"
      image:
        type: string
        description: Image of the article
        example: "https://example.com/article-image.jpg"
      description:
        type: string
        description: Description of the article
        example: "This is the description of the article."
      created_at:
        type: string
        format: date-time
        description: Timestamp when the article was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the article was last updated
        example: "2023-10-02T12:00:00Z"
  CreateFeaturedSectionRequest:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        description: Title of the featured section
  CreateFeaturedSectionResponse:
    type: object
    properties:
      message:
        type: string
        example: "Featured section created successfully."
  GetFeaturedSectionResponse:
    type: object
    properties:
      section:
        $ref: "#/definitions/FeaturedSection"
  GetFeaturedSectionsResponse:
    type: array
    items:
      $ref: "#/definitions/FeaturedSection"
  UpdateFeaturedSectionRequest:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        description: Title of the featured section
  UpdateFeaturedSectionResponse:
    type: object
    properties:
      message:
        type: string
        example: "Featured Section updated successfully."
  UpdateFeaturedArticlesRequest:
    type: array
    items:
      type: string
      format: uuid4
      description: ID of article
      example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
  UpdateFeaturedArticlesResponse:
    type: object
    properties:
      message:
        type: string
        example: "Featured Section articles updated successfully."
  DeleteFeaturedSectionResponse:
    type: object
    properties:
      message:
        type: string
        example: "Section deleted successfully."
  GetFeaturedSectionWithArticlesResponse:
    type: object
    properties:
      featured_section:
        type: object
        $ref: "#/definitions/FeaturedSection"
      articles:
        type: array
        items:
          $ref: "#/definitions/Article"
  GetFeaturedSectionsWithArticlesResponse:
    type: array
    items:
      $ref: "#/definitions/GetFeaturedSectionWithArticlesResponse"
