swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths: {}
definitions:
  NewsCategory:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        description: ID of the news category
        example: 1
      name:
        type: string
        description: Name of the news category
        example: "Politics"
      created_at:
        type: string
        format: date-time
        description: Timestamp when the category was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the category was last updated
        example: "2023-10-02T12:00:00Z"
  NewsArticle:
    type: object
    required:
      - id
      - title
      - content
      - category_id
    properties:
      id:
        type: integer
        description: ID of the news article
        example: 1
      title:
        type: string
        description: Title of the news article
        maxLength: 255
        example: "Breaking News Title"
      content:
        type: string
        description: Content of the news article
        example: "This is the content of the news article."
      category_id:
        type: integer
        description: ID of the category the news article belongs to
        example: 2
      created_at:
        type: string
        format: date-time
        description: Timestamp when the article was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the article was last updated
        example: "2023-10-02T12:00:00Z"
  CreateNewsCategoryResponse:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        description: ID of the created news category
        example: 1
      name:
        type: string
        description: Name of the created news category
        example: "Politics"
      created_at:
        type: string
        format: date-time
        description: Timestamp when the category was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the category was last updated
        example: "2023-10-02T12:00:00Z"
  GetNewsCategoryResponse:
    type: object
    properties:
      category:
        $ref: "#/definitions/NewsCategory"
  UpdateNewsCategoryResponse:
    type: object
    properties:
      category:
        $ref: "#/definitions/NewsCategory"
  DeleteNewsCategoryResponse:
    type: object
    properties:
      message:
        type: string
        example: "Category deleted successfully."
  GetCategoryWithNewsResponse:
    type: object
    properties:
      category_id:
        type: integer
        example: 1
      category_name:
        type: string
        example: "Politics"
      news:
        type: array
        items:
          $ref: "#/definitions/NewsArticle"
  GetAllCategoriesWithNewsResponse:
    type: array
    items:
      type: object
      properties:
        category_id:
          type: integer
          example: 1
        category_name:
          type: string
          example: "Politics"
        news_id:
          type: integer
          example: 1
        news_title:
          type: string
          example: "Breaking News Title"
        news_content:
          type: string
          example: "This is the content of the news article."
        news_created_at:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
        news_updated_at:
          type: string
          format: date-time
          example: "2023-10-02T12:00:00Z"
