swagger: "2.0"
info:
  title: ""
  version: 0.1.0
paths: {}
definitions:
  Stream:
    type: object
    required:
      - id
      - userID
      - name
      - url
      - thumbnail
      - status
      - viewers
    properties:
      id:
        type: string
        format: uuid4
      userID:
        type: string
        format: uuid4
      app:
        type: string
      name:
        type: string
      url:
        type: string
      password:
        type: string
      host:
        type: string
      endpoint:
        type: string
      thumbnail:
        type: string
      status:
        type: string
      viewers:
        type: string
      lastPublishedAt:
        type: string
      liveTitle:
        type: string
      liveDescription:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string

  StreamPayload:
    type: object
    required:
      - userID
      - name
      - url
      - thumbnail
      - status
      - viewers
    properties:
      userID:
        type: string
        format: uuid4
      app:
        type: string
      name:
        type: string
      url:
        type: string
      password:
        type: string
      thumbnail:
        type: string
      status:
        type: string
      viewers:
        type: string
      lastPublishedAt:
        type: string
      liveTitle:
        type: string
      liveDescription:
        type: string

  UpdateStreamPayload:
    type: object
    properties:
      thumbnail:
        type: string
      liveTitle:
        type: string
      liveDescription:
        type: string
  UpdateStreamNamePayload:
    type: object
    required:
      - name
    properties:
      name:
        type: string

  CreateStreamPayload:
    type: object
    required:
      - name
    properties:
      name:
        type: string

  StreamList:
    type: array
    items:
      $ref: "#/definitions/Stream"
  StreamEvent:
    type: object
    required:
      - request_id
      - action
      - vhost
      - app
      - stream
    properties:
      request_id:
        description: Unique identifier for the request
        type: string
        example: 3ab26a09-59b0-42f7-98e3-a281c7d0712b
      action:
        description: Action performed on the stream
        type: string
        example: on_publish
      opaque:
        description: Optional opaque token
        type: string
        example: mytoken
      vhost:
        description: Virtual host of the stream
        type: string
        example: __defaultVhost__
      app:
        description: Application name of the stream
        type: string
        example: live
      stream:
        description: Stream name
        type: string
        example: livestream
      param:
        description: Parameters passed to the stream
        type: string
        example: "?secret=8f7605d657c74d69b6b48f532c469bc9"
  StreamEventResponse:
    type: object
    required:
      - code
    properties:
      code:
        description: Response code
        type: integer
        example: 0
