swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths: {}
definitions:
  Stream:
    type: object
    required:
      - id
      - app
      - stream_name
      - url
      - user_id
    properties:
      id:
        type: string
        format: uuid4
        description: ID of stream
        example: 891d37d3-c74f-493e-aea8-af73efd92016
      app:
        description: App of stream
        type: string
        maxLength: 255
        minLength: 1
        example: app
      stream_name:
        description: Stream name of stream
        type: string
        maxLength: 255
        minLength: 1
        example: stream_name
      url:
        description: URL of stream
        type: string
        maxLength: 255
        minLength: 1
        example: url
      user_id:
        description: User ID of stream
        type: string
        format: uuid4
        example: 891d37d3-c74f-493e-aea8-af73efd92016
  StreamEvent:
    type: object
    required:
      - request_id
      - action
      - vhost
      - app
      - stream
      - param
    properties:
      request_id:
        description: Unique identifier for the request
        type: string
        example: 3ab26a09-59b0-42f7-98e3-a281c7d0712b
      action:
        description: Action performed on the stream
        type: string
        example: on_publish
      opaque:
        description: Optional opaque token
        type: string
        example: mytoken
      vhost:
        description: Virtual host of the stream
        type: string
        example: __defaultVhost__
      app:
        description: Application name of the stream
        type: string
        example: live
      stream:
        description: Stream name
        type: string
        example: livestream
      param:
        description: Parameters passed to the stream
        type: string
        example: "?secret=8f7605d657c74d69b6b48f532c469bc9"
  StreamEventResponse:
    type: object
    required:
      - code
    properties:
      code:
        description: Response code
        type: integer
        example: 0
  CreateStreamResponse:
    type: object
    required:
      - id
    properties:
      id:
        description: ID of stream
        type: string
        format: uuid4
        example: 891d37d3-c74f-493e-aea8-af73efd92016
      url:
        description: URL of stream
        type: string
        example: url
