swagger: "2.0"
info:
  title: github.com/JehadAbdulwafi/rustion
  version: 0.1.0
paths: {}
definitions:
  Tag:
    type: object
    required:
      - id
      - title
      - app_id
    properties:
      id:
        type: string
        format: uuid4
        description: ID of tag
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      app_id:
        type: string
        format: uuid4
        description: ID of app
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      title:
        type: string
        description: Name of the tag
        example: "Politics"
      created_at:
        type: string
        format: date-time
        description: Timestamp when the tag was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the tag was last updated
        example: "2023-10-02T12:00:00Z"
  Article:
    type: object
    required:
      - id
      - title
      - content
      - image
      - app_id
    properties:
      id:
        type: string
        format: uuid4
        description: ID of article
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      app_id:
        type: string
        format: uuid4
        description: ID of app
        example: 82ebdfad-c586-4407-a873-4cc1c33d56fc
      title:
        type: string
        description: Title of the article
        maxLength: 255
        example: "Article Title"
      content:
        type: string
        description: Content of the article
        example: "This is the content of the article."
      tags:
        type: string
        description: Content of the article
        example: "tag1,tag2,tag3"
      image:
        type: string
        description: Image of the article
        example: "https://example.com/article-image.jpg"
      description:
        type: string
        description: Description of the article
        example: "This is the description of the article."
      created_at:
        type: string
        format: date-time
        description: Timestamp when the article was created
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        description: Timestamp when the article was last updated
        example: "2023-10-02T12:00:00Z"
  CreateTagRequest:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        description: Name of the tag
        example: "Politics"
  UpdateTagRequest:
    type: object
    required:
      - title
    properties:
      title:
        type: string
        description: Name of the tag
        example: "Politics"
  GetTagResponse:
    type: object
    properties:
      tag:
        $ref: "#/definitions/Tag"
  GetTagsResponse:
    type: array
    items:
      $ref: "#/definitions/Tag"
  GetTagWithArticlesResponse:
    type: object
    properties:
      tag:
        type: object
        $ref: "#/definitions/Tag"
      articles:
        type: array
        items:
          $ref: "#/definitions/Article"
  GetTagsWithArticlesResponse:
    type: array
    items:
      $ref: "#/definitions/GetTagWithArticlesResponse"
